#!/usr/bin/env sh

if [[ ! -n $1 ]]; then
	echo "ipadump <source.app> [target.ipa]"
	exit
fi

if [[ ! -n $2 ]]; then
	target_ipa=$1
else
	target_ipa=$2
fi

abs_target_ipa=$(cd "$(dirname "$target_ipa")"; pwd)/$(basename "$target_ipa")

cd $HOME
if [[ ! -d ".ipadump" ]]; then
	git clone https://github.com/AloneMonkey/frida-ios-dump.git .ipadump
fi

cd .ipadump
pipenv install
pipenv run ./dump.py -o $abs_target_ipa $1