#!/usr/bin/env sh

set -e
set -o pipefail

is_remove_plugin_and_watch=false

Usage() {
	echo "Usage:
dumpipa [-r] <app_name|app_bundleid> [target.ipa]
dumpapp [-r] <app_name|app_bundleid> [target.app]
ipa2app [-r] <source.ipa> [target.app]
app2ipa [-r] <source.app> [target.ipa]
server
-r, remove plugin and watch"
}

while getopts r opt; do
    case $opt in
    	r)
		is_remove_plugin_and_watch=true
		;;
    esac
done

shift $[ $OPTIND -1 ]

_dump() {
	if [[ ! -n $2 ]]; then
		target_ipa=$1
	else
		target_ipa=$2
	fi
	abs_target_ipa=$(cd "$(dirname "$target_ipa")"; pwd)/$(basename "$target_ipa")

	# cd $HOME
	# if [[ ! -d .ipatool ]]; then
	# 	git clone https://github.com/AloneMonkey/frida-ios-dump.git .ipatool
	# 	cd $HOME/.ipatool
	# 	pipenv install
	# fi
	# cd $HOME/.ipatool
	# pipenv run ./dump.py $1 -o $2
	echo $abs_target_ipa
}

_remove_plugin_and_watch() {
	echo ""
}

if [[ $1 == "dumpipa" ]]; then
	echo "dumpipa"
	ipa=$(_dump $2 $3)
	echo $is_remove_plugin_and_watch
	if [[ $is_remove_plugin_and_watch == true ]]; then
		echo "remove true"
	fi
	echo $ipa
elif [[ $1 == "dumpapp" ]]; then
	echo "dumpapp"
	ipa=$(_dump $2 $3)
	echo $ipa
elif [[ $1 == "app2ipa" ]]; then
	echo "app2ipa"
elif [[ $1 == "ipa2app" ]]; then
	echo "ipa2app"
elif [[ $1 == "server" ]]; then
	/usr/local/bin/iproxy 2222:22
else
	Usage
fi
