#!/usr/bin/env sh

set -e
set -o pipefail

is_remove_plugin_and_watch=false

Usage() {
	echo "Usage:
dumpipa <app_name|app_bundleid> [target.ipa]
ipa2app <source.ipa> [target.app]
app2ipa <source.app> [target.ipa]
server
-r, remove plugin and watch"
}

while getopts r opt; do
    case $opt in
    	r)
		is_remove_plugin_and_watch=true
		;;
    esac
done

shift $[ $OPTIND -1 ]

_dump() {
	if [[ ! -n $1 ]]; then
		echo "ipatool dump <source.app> [target.ipa]"
		exit 0
	fi

	if [[ ! -n $2 ]]; then
		target_ipa=$1
	else
		target_ipa=$2
	fi

	abs_target_ipa=$(cd "$(dirname "$target_ipa")"; pwd)/$(basename "$target_ipa")

	# cd $HOME
	# if [[ ! -d .ipatool ]]; then
	# 	git clone https://github.com/AloneMonkey/frida-ios-dump.git .ipatool
	# 	cd $HOME/.ipatool
	# 	pipenv install
	# fi
	# cd $HOME/.ipatool
	# pipenv run ./dump.py $1 -o $2
	echo $abs_target_ipa
}

_app2ipa() {
	if [[ ! -n $1 ]] || [[ ! -n $2 ]]; then
		echo "app2ipa <source.app> <target.ipa>"
	elif [ ! -d $1 ]; then
		echo "source.app not exist"
	else
		mkdir Payload; cp -r $1 Payload; zip -r $2 Payload; rm -r Payload
	fi
}

_ipa2app() {
	if [[ ! -n $1 ]]; then
		echo "ipa2app <source.ipa>"
	else
		unzip $1; mv Payload/*.app ./; rm -rf Payload
	fi
}

_remove_plugin_and_watch() {
	rm -rf $1/PlugIns
	rm -rf $1/Watch
}

if [[ $1 == "dump" ]]; then
	_dump $2 $3
elif [[ $1 == "app2ipa" ]]; then
	_app2ipa $2 $3
elif [[ $1 == "ipa2app" ]]; then
	_ipa2app $2 $3
elif [[ $1 == "server" ]]; then
	/usr/local/bin/iproxy 2222:22
else
	Usage
fi
